name: Build Android APK with Briefcase

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_HOME: /opt/android-sdk
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgirepository1.0-dev \
          libc6-dev \
          libffi-dev \
          libssl-dev \
          python3-dev \
          build-essential \
          git \
          unzip \
          curl
        
    - name: Setup Android SDK manually
      run: |
        sudo mkdir -p $ANDROID_SDK_ROOT
        sudo chown -R $USER:$USER $ANDROID_SDK_ROOT
        cd /tmp
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        mv cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
        echo "export PATH=\$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
    - name: Install Android SDK components
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0"
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install briefcase
        
    - name: Create Android project
      run: briefcase create android
      
    - name: Build Android project  
      run: briefcase build android
      
    - name: Package Android APK
      run: briefcase package android --adhoc-sign
      
    - name: Find and move APK
      run: |
        find . -name "*.apk" -type f
        mkdir -p dist
        find . -name "*.apk" -type f -exec cp {} dist/ \;
        ls -la dist/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: "dist/*.apk"
        retention-days: 30
