name: Build APK Simple

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create files
      run: |
        # Main Python file
        cat > main.py << 'EOF'
        from kivy.app import App
        from kivy.uix.label import Label
        
        class SimpleApp(App):
            def build(self):
                return Label(text='YouTube Downloader\nFunziona!')
        
        SimpleApp().run()
        EOF
        
        # Buildozer spec
        cat > buildozer.spec << 'EOF'
        [app]
        title = YouTubeDownloader
        package.name = ytdownloader
        package.domain = org.test
        source.dir = .
        source.include_exts = py
        version = 0.1
        requirements = python3,kivy
        
        [buildozer]
        log_level = 1
        EOF
    
    - name: Build APK
      uses: RoyalHollowayCS/buildozer-action@v1.0.0
      with:
        command: buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
